"""Central limits and defaults for notebook analysis."""

from .execution import DEFAULT_NOTEBOOK_IMAGE, ExecutionLimits

MAX_DEFAULT_RESULTS = 10
MAX_WORKSPACE_FILES = 20
MAX_WORKSPACE_FILE_BYTES = 10 * 1024 * 1024
MAX_WORKSPACE_TOTAL_BYTES = 50 * 1024 * 1024
MAX_CELLS = 30
MAX_CELL_SOURCE_CHARS = 20_000
MAX_TOTAL_SOURCE_CHARS = 120_000
MAX_OUTPUT_CHARS = 3_000
MAX_SNAPSHOT_CHARS = 40_000
MAX_SNAPSHOT_IMAGES = 8
MAX_IMAGE_BYTES = 2 * 1024 * 1024
MAX_SNAPSHOT_IMAGE_BYTES = 8 * 1024 * 1024
MAX_HISTORY_IMAGE_BYTES = 16 * 1024 * 1024
MAX_IMAGE_WIDTH = 2048
MAX_IMAGE_HEIGHT = 2048
MAX_GOAL_CHARS = 20_000
MAX_MODEL_REQUESTS = 25
DEFAULT_ANALYSIS_TIMEOUT_SECONDS = 900
DEFAULT_OPERATION_TIMEOUT_SECONDS = 1500
DEFAULT_EXECUTION_LIMITS = ExecutionLimits()

__all__ = [
    "DEFAULT_ANALYSIS_TIMEOUT_SECONDS",
    "DEFAULT_EXECUTION_LIMITS",
    "DEFAULT_NOTEBOOK_IMAGE",
    "DEFAULT_OPERATION_TIMEOUT_SECONDS",
    "MAX_CELLS",
    "MAX_CELL_SOURCE_CHARS",
    "MAX_GOAL_CHARS",
    "MAX_HISTORY_IMAGE_BYTES",
    "MAX_IMAGE_BYTES",
    "MAX_IMAGE_HEIGHT",
    "MAX_IMAGE_WIDTH",
    "MAX_MODEL_REQUESTS",
    "MAX_OUTPUT_CHARS",
    "MAX_SNAPSHOT_CHARS",
    "MAX_SNAPSHOT_IMAGE_BYTES",
    "MAX_SNAPSHOT_IMAGES",
    "MAX_TOTAL_SOURCE_CHARS",
    "MAX_WORKSPACE_FILES",
    "MAX_WORKSPACE_FILE_BYTES",
    "MAX_WORKSPACE_TOTAL_BYTES",
]
