"""Central limits and defaults for notebook analysis."""

from .config import DEFAULT_NOTEBOOK_CONFIG
from .execution import DEFAULT_NOTEBOOK_IMAGE, ExecutionLimits

# Balanced defaults target larger EDA and classical ML while retaining finite
# model-context, host-memory, runtime, and cost boundaries.
MAX_WORKSPACE_FILES = DEFAULT_NOTEBOOK_CONFIG.workspace.max_files
MAX_WORKSPACE_FILE_BYTES = DEFAULT_NOTEBOOK_CONFIG.workspace.max_file_bytes
MAX_WORKSPACE_TOTAL_BYTES = DEFAULT_NOTEBOOK_CONFIG.workspace.max_total_bytes
MAX_WORKSPACE_MANIFEST_BYTES = DEFAULT_NOTEBOOK_CONFIG.workspace.max_manifest_bytes
MAX_CELL_SOURCE_CHARS = 30_000
MAX_TOTAL_SOURCE_CHARS = 200_000
MAX_OUTPUT_CHARS = 6_000
MAX_SNAPSHOT_CHARS = 80_000
MAX_SNAPSHOT_IMAGES = 12
MAX_IMAGE_BYTES = 4 * 1024 * 1024
MAX_SNAPSHOT_IMAGE_BYTES = 24 * 1024 * 1024
MAX_HISTORY_IMAGE_BYTES = 48 * 1024 * 1024
MAX_IMAGE_WIDTH = 2048
MAX_IMAGE_HEIGHT = 2048
MAX_GOAL_CHARS = 20_000
DEFAULT_EXECUTION_LIMITS = ExecutionLimits()

__all__ = [
    "DEFAULT_EXECUTION_LIMITS",
    "DEFAULT_NOTEBOOK_IMAGE",
    "MAX_CELL_SOURCE_CHARS",
    "MAX_GOAL_CHARS",
    "MAX_HISTORY_IMAGE_BYTES",
    "MAX_IMAGE_BYTES",
    "MAX_IMAGE_HEIGHT",
    "MAX_IMAGE_WIDTH",
    "MAX_OUTPUT_CHARS",
    "MAX_SNAPSHOT_CHARS",
    "MAX_SNAPSHOT_IMAGE_BYTES",
    "MAX_SNAPSHOT_IMAGES",
    "MAX_TOTAL_SOURCE_CHARS",
    "MAX_WORKSPACE_FILES",
    "MAX_WORKSPACE_MANIFEST_BYTES",
    "MAX_WORKSPACE_FILE_BYTES",
    "MAX_WORKSPACE_TOTAL_BYTES",
]
